// <auto-generated />
using System;
using Ecommerce.Infrastructure.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Infrastructure.Migrations
{
    [DbContext(typeof(EcommerceDbContext))]
    partial class EcommerceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f382d6f5-37e9-4ae1-b957-6df092654021"),
                            CategoryName = "Books"
                        },
                        new
                        {
                            Id = new Guid("738bff8a-b670-4d29-af79-9eb31058dd64"),
                            CategoryName = "Mobiles, Computers"
                        },
                        new
                        {
                            Id = new Guid("9a3768da-4464-4702-b24d-48288dd96eb0"),
                            CategoryName = "TV, Appliances, Electronics"
                        },
                        new
                        {
                            Id = new Guid("2aef81d8-f6f9-4dd1-ad4b-377f2996ac02"),
                            CategoryName = "Men's Fashion"
                        },
                        new
                        {
                            Id = new Guid("3f85c6ef-0e1b-449b-8f15-989575379024"),
                            CategoryName = "Women's Fashion"
                        },
                        new
                        {
                            Id = new Guid("7eef79a6-745a-4c4e-8d9c-99d71bb4ccd5"),
                            CategoryName = "Toy, Baby Products, Kid's Fashion"
                        });
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf4f4572-30fc-4783-9bd3-f0eef99c7723"),
                            CategoryId = new Guid("f382d6f5-37e9-4ae1-b957-6df092654021"),
                            Price = 2500L,
                            ProductName = "System Design By Paritosh Gupta",
                            ProductType = "TextBooks"
                        },
                        new
                        {
                            Id = new Guid("414fb751-5548-4b76-b9d5-d2fb0f7d1de4"),
                            CategoryId = new Guid("f382d6f5-37e9-4ae1-b957-6df092654021"),
                            Price = 250L,
                            ProductName = "Two States By Chetan Bhagat",
                            ProductType = "FictionBooks"
                        },
                        new
                        {
                            Id = new Guid("a0bd54bc-a197-49ad-b5dc-f6f6c623e297"),
                            CategoryId = new Guid("f382d6f5-37e9-4ae1-b957-6df092654021"),
                            Price = 500L,
                            ProductName = "Harry Potter and the Philosopher Stone by J.K. Rowling",
                            ProductType = "KidsBooks"
                        },
                        new
                        {
                            Id = new Guid("dc57f3ff-df12-42ef-a8b9-39c67b7320c9"),
                            CategoryId = new Guid("738bff8a-b670-4d29-af79-9eb31058dd64"),
                            Price = 30000L,
                            ProductName = "IQOO Z6",
                            ProductType = "Mobiles"
                        },
                        new
                        {
                            Id = new Guid("62707d45-cdd5-4f2f-b1d2-e05f9f1ef149"),
                            CategoryId = new Guid("738bff8a-b670-4d29-af79-9eb31058dd64"),
                            Price = 18000L,
                            ProductName = "Samsung Galaxy Tab A9+",
                            ProductType = "Tablets"
                        },
                        new
                        {
                            Id = new Guid("8cee5fc7-2773-43de-b2db-8b0e5ff60710"),
                            CategoryId = new Guid("2aef81d8-f6f9-4dd1-ad4b-377f2996ac02"),
                            Price = 11997L,
                            ProductName = "Fossil Gen 6 Digital Black Dial Men's Watch-FTW4061",
                            ProductType = " MensWatches"
                        },
                        new
                        {
                            Id = new Guid("8f568a3c-c327-4e8c-8802-e63e2b2406da"),
                            CategoryId = new Guid("3f85c6ef-0e1b-449b-8f15-989575379024"),
                            Price = 1197L,
                            ProductName = "Fastrack New Limitless FS1 Smart Watch",
                            ProductType = " WomensWatches"
                        });
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.Product", b =>
                {
                    b.HasOne("Ecommerce.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
